set_property PACKAGE_PIN P18 [get_ports Dbun]
set_property PACKAGE_PIN M18 [get_ports Ubun]
set_property PACKAGE_PIN M17 [get_ports Rbun]

set_property PACKAGE_PIN D17 [get_ports cam_rstn]
set_property PACKAGE_PIN C17 [get_ports cam_pwdn]
set_property PACKAGE_PIN E16 [get_ports cam_clk]
set_property PACKAGE_PIN H16 [get_ports cam_in_clk]
set_property PACKAGE_PIN G16 [get_ports cam_href]
set_property PACKAGE_PIN F13 [get_ports cam_vsynk]
set_property PACKAGE_PIN G13 [get_ports SCCB_CLK]
set_property PACKAGE_PIN H14 [get_ports SCCB_DATA]
set_property PACKAGE_PIN D14 [get_ports {cam_data[7]}]
set_property PACKAGE_PIN F16 [get_ports {cam_data[6]}]
set_property PACKAGE_PIN G18 [get_ports {cam_data[5]}]
set_property PACKAGE_PIN G17 [get_ports {cam_data[4]}]
set_property PACKAGE_PIN F18 [get_ports {cam_data[3]}]
set_property PACKAGE_PIN E18 [get_ports {cam_data[2]}]
set_property PACKAGE_PIN E17 [get_ports {cam_data[1]}]
set_property PACKAGE_PIN D18 [get_ports {cam_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports Dbun]
set_property IOSTANDARD LVCMOS33 [get_ports Ubun]
set_property IOSTANDARD LVCMOS33 [get_ports Rbun]
set_property IOSTANDARD LVCMOS33 [get_ports cam_rstn]
set_property IOSTANDARD LVCMOS33 [get_ports cam_pwdn]
set_property IOSTANDARD LVCMOS33 [get_ports cam_clk]
set_property IOSTANDARD LVCMOS33 [get_ports cam_in_clk]
set_property IOSTANDARD LVCMOS33 [get_ports cam_href]
set_property IOSTANDARD LVCMOS33 [get_ports cam_vsynk]
set_property IOSTANDARD LVCMOS33 [get_ports SCCB_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports SCCB_DATA]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam_data[0]}]

set_property PACKAGE_PIN D8 [get_ports {BLU[3]}]
set_property PACKAGE_PIN D7 [get_ports {BLU[2]}]
set_property PACKAGE_PIN C7 [get_ports {BLU[1]}]
set_property PACKAGE_PIN B7 [get_ports {BLU[0]}]
set_property PACKAGE_PIN A6 [get_ports {GRN[3]}]
set_property PACKAGE_PIN B6 [get_ports {GRN[2]}]
set_property PACKAGE_PIN A5 [get_ports {GRN[1]}]
set_property PACKAGE_PIN C6 [get_ports {GRN[0]}]
set_property PACKAGE_PIN A4 [get_ports {RED[3]}]
set_property PACKAGE_PIN C5 [get_ports {RED[2]}]
set_property PACKAGE_PIN B4 [get_ports {RED[1]}]
set_property PACKAGE_PIN A3 [get_ports {RED[0]}]
set_property PACKAGE_PIN B11 [get_ports HSYNC]
set_property PACKAGE_PIN B12 [get_ports VSYNC]

set_property IOSTANDARD LVCMOS33 [get_ports {BLU[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLU[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLU[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {BLU[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GRN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GRN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GRN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GRN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports HSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports VSYNC]

set_property PACKAGE_PIN A13 [get_ports DeBug_cam_clk]
set_property PACKAGE_PIN A14 [get_ports DeBug_cam_in_clk]
set_property IOSTANDARD LVCMOS33 [get_ports DeBug_cam_clk]
set_property IOSTANDARD LVCMOS33 [get_ports DeBug_cam_in_clk]
set_property PACKAGE_PIN A15 [get_ports DeBug_cam_vsynk]
set_property PACKAGE_PIN A16 [get_ports DeBug_VSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports DeBug_cam_vsynk]
set_property IOSTANDARD LVCMOS33 [get_ports DeBug_VSYNC]
set_property PACKAGE_PIN B16 [get_ports DeBug_cam_href]
set_property PACKAGE_PIN B17 [get_ports DeBug_HSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports DeBug_cam_href]
set_property IOSTANDARD LVCMOS33 [get_ports DeBug_HSYNC]

set_property PULLUP true [get_ports SCCB_DATA]
set_property PULLDOWN true [get_ports cam_in_clk]


set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
